"""Atomic, reviewable evidence objects for MagicForge."""

from knowledge.evidence import (
    ApplicationOrigin,
    ClaimRole,
    ClaimPolarity,
    ConfidenceAssessment,
    ConfidenceDimension,
    ConfidenceLabel,
    ContradictionStatus,
    EvidenceCard,
    EvidenceClass,
    EvidenceLevel,
    EvidenceLocator,
    EvidenceReview,
    EvidenceSource,
    KnowledgeOrigin,
    MagicDomain,
    MechanismStatus,
    SourceType,
    classification_for_evidence_class,
)

__all__ = [
    "ApplicationOrigin",
    "ClaimRole",
    "ClaimPolarity",
    "ConfidenceAssessment",
    "ConfidenceDimension",
    "ConfidenceLabel",
    "ContradictionStatus",
    "EvidenceCard",
    "EvidenceClass",
    "EvidenceLevel",
    "EvidenceLocator",
    "EvidenceReview",
    "EvidenceSource",
    "KnowledgeOrigin",
    "MagicDomain",
    "MechanismStatus",
    "SourceType",
    "classification_for_evidence_class",
]
