"""MagicForge authentication and authorization primitives."""

from security.crypto import (
    IssuedTokens,
    PasswordHasher,
    PasswordPolicyError,
    TokenFactory,
    hash_token,
    token_hashes_equal,
)
from security.repositories import (
    RoleRepository,
    SessionRepository,
    UserRepository,
    normalize_identifier,
)
from security.services import (
    AdminService,
    AuthorizationDeniedError,
    AuthService,
    CsrfValidationError,
    InvalidCredentialsError,
    RoleChangeResult,
    SecurityInputError,
    SecurityResourceNotFoundError,
    SecurityServiceError,
    SecurityStateConflictError,
    SessionCredentials,
    SessionRevocationResult,
    UnauthenticatedError,
    UserSummary,
)
from security.policy import (
    AccessDeniedError,
    AuthenticatedActor,
    AuthenticationRequiredError,
    AuthorizationError,
    BreakGlassPolicyError,
    Permission,
    activate_break_glass,
    bootstrap_anonymous_actor,
    bootstrap_anonymous_retrieval_authorization,
    has_permission,
    permissions_for_actor,
    require_permission,
    retrieval_authorization_for_actor,
)

__all__ = [
    "IssuedTokens",
    "AdminService",
    "AuthorizationDeniedError",
    "AuthService",
    "CsrfValidationError",
    "InvalidCredentialsError",
    "AccessDeniedError",
    "AuthenticatedActor",
    "AuthenticationRequiredError",
    "AuthorizationError",
    "BreakGlassPolicyError",
    "Permission",
    "PasswordHasher",
    "PasswordPolicyError",
    "RoleRepository",
    "RoleChangeResult",
    "SecurityInputError",
    "SecurityResourceNotFoundError",
    "SecurityServiceError",
    "SecurityStateConflictError",
    "SessionRepository",
    "SessionCredentials",
    "SessionRevocationResult",
    "TokenFactory",
    "UserRepository",
    "UnauthenticatedError",
    "UserSummary",
    "hash_token",
    "normalize_identifier",
    "token_hashes_equal",
    "activate_break_glass",
    "bootstrap_anonymous_actor",
    "bootstrap_anonymous_retrieval_authorization",
    "has_permission",
    "permissions_for_actor",
    "require_permission",
    "retrieval_authorization_for_actor",
]
