"""Strict, local-first primitives for MagicForge localization."""

from localization.pipeline.models import (
    BatchValidationRequest,
    GenerationOrigin,
    GovernedTerm,
    LocalizationIssueType,
    LocalizationAction,
    LocalizationClassification,
    PolicyIndex,
    ProposalStatus,
    QualityReviewDecision,
    QualityReviewDisposition,
    QualityReviewNormalization,
    SourceUnit,
    TermStatus,
    TranslationProposal,
    ValidationIssue,
    ValidationReport,
    ValidationSeverity,
    compute_source_hash,
    extract_placeholders,
)
from localization.pipeline.policy import PolicyConfigurationError, load_policy_index
from localization.pipeline.validator import LocalizationValidator

__all__ = [
    "BatchValidationRequest",
    "GenerationOrigin",
    "GovernedTerm",
    "LocalizationIssueType",
    "LocalizationAction",
    "LocalizationClassification",
    "LocalizationValidator",
    "PolicyConfigurationError",
    "PolicyIndex",
    "ProposalStatus",
    "QualityReviewDecision",
    "QualityReviewDisposition",
    "QualityReviewNormalization",
    "SourceUnit",
    "TermStatus",
    "TranslationProposal",
    "ValidationIssue",
    "ValidationReport",
    "ValidationSeverity",
    "compute_source_hash",
    "extract_placeholders",
    "load_policy_index",
]
